-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 23:00:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola` DEFAULT CHARACTER SET utf8 ;
USE `db_escola` ;

-- -----------------------------------------------------
-- Table `db_escola`.`tb_alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_alunos` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nota` FLOAT NOT NULL,
  `idade` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_escola`.`tb_alunos`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_escola`;
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'larissa', 7, 17, 'feminino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'silas', 8, 18, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'leo', 5, 20, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'jp', 10, 23, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'River', 8, 25, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'Leandro', 7, 17, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'je', 6, 16, 'masculino');
INSERT INTO `db_escola`.`tb_alunos` (`id_aluno`, `nome`, `nota`, `idade`, `genero`) VALUES (DEFAULT, 'Ro', 5, 18, 'masculino');


COMMIT;

